version: "3"
services: 

  app:
    build: .
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ADDRESS: ${DB_ADDRESS}
      DB_NAME: ${DB_NAME}
      S3_REGION: ${S3_REGION}
      S3_KEY_ID: ${S3_KEY_ID}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - 80:80