version: "3"
services: 

  app:
    build: .
    restart: always
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin12345
      DB_ADDRESS: project-capstone-group4.cxnxi7fi64g5.ap-southeast-1.rds.amazonaws.com
      DB_NAME: project-capstone
      S3_REGION: ap-southeast-1
      S3_KEY_ID: AKIAT4S5BF6ACXY5VUH3
      S3_ACCESS_KEY: x50JQ4bNd9BbJLsLbr1PIB+nuyXjbiEa08/TuWXT
      S3_BUCKET_NAME: project-capstone-group4
    ports:
      - 8080:8080
  
volumes:
  my-datavolume: